embedding_size: 64
feat_embed_dim: 64
weight_size: [64, 64]

learning_rate_scheduler: [0.96, 50]
lambda_coeff: 0.9
learning_rate: 0.001
# learning_rate: [0.1,0.01,0.001,0.0001]

# lambda2: [0.5]
# lambda2: [0.1]
# lambda2: [0.005,0.01,0.05,0.1]
# lambda2: [0.005,0.01,0.05,0.1,0.15]
# lambda2: 
n_mm_layers: 1
n_ui_layers: 2
knn_k: 10

mm_image_weight: 0.1
lambda1: [0.01,0.05, 0.001, 0.005, 0.0001]
dropout: [0.05, 0.1, 0.15, 0.2]
# dropout: [0.15, 0.2, 0.3]
lambda2: [0.05, 0.1, 0.2, 0.3, 0.4, 0.5]
# num_heads: [1, 2, 4, 6, 8, 10]
num_heads: 4
# temp: [0.2, 0.3, 0.4, 0.5]
temp: 0.2

hyper_parameters: ["dropout", "lambda1","lambda2"]